<!doctype html>
<html lang="id">

<head>
    <meta charset="utf-8">
    <title>SK - {{ $sk->nomor_sk ?? '-' }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #111;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .title {
            font-size: 18px;
            font-weight: 700;
        }

        .sub {
            font-size: 12px;
            color: #555;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        td,
        th {
            padding: 8px 6px;
            vertical-align: top;
        }

        .bdr {
            border: 1px solid #333;
        }

        .center {
            text-align: center;
        }

        .right {
            text-align: right;
        }

        .sign {
            margin-top: 40px;
            width: 100%;
            display: flex;
            justify-content: space-between;
        }

        .sign .block {
            width: 40%;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">SURAT KEPUTUSAN</div>
        <div class="sub">Nomor: {{ $sk->nomor_sk ?? '-' }}</div>
        <div class="sub">Tanggal: {{ optional($sk->tanggal_sk)->format('d-m-Y') ?? (isset($sk->created_at) ? $sk->created_at->format('d-m-Y') : '-') }}</div>
    </div>

    <p>Menetapkan:</p>

    <table class="bdr">
        <tr>
            <th style="width:30%;">Mata Kuliah</th>
            <td>{{ optional($sk->ploting)->matakuliah->nama ?? optional($sk->ploting)->matakuliah_id ?? '-' }}</td>
        </tr>
        <tr>
            <th>Kode MK</th>
            <td>{{ optional($sk->ploting)->matakuliah->kode_mk ?? '-' }}</td>
        </tr>
        <tr>
            <th>Dosen</th>
            <td>{{ optional($sk->ploting)->dosen->name ?? '-' }}</td>
        </tr>
        <tr>
            <th>Kelas</th>
            <td>
                {{ optional($sk->ploting)->kelas->nama ?? optional($sk->ploting)->kelas ?? optional($sk->ploting)->kelas_id ?? '-' }}
            </td>
        </tr>
        <tr>
            <th>Semester / Tahun</th>
            <td>{{ optional($sk->ploting)->semester ?? '-' }} / {{ optional($sk->ploting)->tahun_akademik ?? '-' }}</td>
        </tr>
        <tr>
            <th>Status Dekan</th>
            <td>{{ $sk->status_dekan ?? '-' }}</td>
        </tr>
        <tr>
            <th>Status WR1</th>
            <td>{{ $sk->status_warek1 ?? '-' }}</td>
        </tr>
    </table>

    <p style="margin-top:18px;">
        Dengan ini ditetapkan keputusan penugasan mengajar sebagaimana tercantum di atas.
    </p>

    <div class="sign">
        <div class="block">
            <div>Mengetahui,</div>
            <div style="margin-top:40px;"><strong>Dekan</strong></div>
            <div style="margin-top:6px;">(...................................)</div>
        </div>

        <div class="block">
            <div>Disetujui,</div>
            <div style="margin-top:40px;"><strong>Wakil Rektor I</strong></div>
            <div style="margin-top:6px;">(...................................)</div>
        </div>
    </div>

    <p style="font-size:10px; color:#666; margin-top:30px;">
        Generated by SIAKAD — Mandala
    </p>
</body>

</html>